# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-24.04
  tools:
    nodejs: "22"
  commands:
    # Install vitepress and build the docs
    - npm install -g vitepress@2.0.0-alpha.16; npm run docs:build
    # Copy the output to Read the Docs expected location
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp -r docs/.vitepress/dist/. "$READTHEDOCS_OUTPUT/html"
    # Clean up build artifacts
    - rm -rf docs/.vitepress
